name: Terratest
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  TF_VAR_shared_vpc_host_google_project: ${{ secrets.TF_VAR_shared_vpc_host_google_project }}
  TF_VAR_shared_vpc_host_google_credentials: ${{ secrets.TF_VAR_shared_vpc_host_google_credentials }}
  TF_VAR_google_region: "asia-southeast2"
jobs:
  go:
    name: terratest
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up kubeconfig
        run: |
          mkdir /home/runner/.kube
          touch /home/runner/.kube/config
      - name: Login to Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "latest" # This is the default value anyways, just being explicit
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          export_default_credentials: false
      - name: Set Google Cloud project
        run: gcloud config set project ${{ secrets.GOOGLE_PROJECT }}
      - name: Set up Go (1.15)
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Get Go dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Run 'go test -v -timeout 30m'
        run: |
          cd test
          go test -v -timeout 30m
